### ISSUE TITLE
the "make" procedure fail

### ISSUE THREAD

**Issue by pilot513** [maxbube/mydumper#120]
Hello.
When I try build on OEL 7.4 get error

Scanning dependencies of target mydumper
[ 25%] Building C object CMakeFiles/mydumper.dir/mydumper.c.o
/home/user/dumper.0.9.3/mydumper-master/mydumper.c: In function ‘dump_table_data’:
/home/user/dumper.0.9.3/mydumper-master/mydumper.c:2821:55: error: ‘MYSQL_TYPE_JSON’ undeclared (first use in this function)
                                 if (fields[i].type == MYSQL_TYPE_JSON) g_string_append(statement_row, "CONVERT(");
                                                       ^
/home/user/dumper.0.9.3/mydumper-master/mydumper.c:2821:55: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/mydumper.dir/mydumper.c.o] Error 1
make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
make: *** [all] Error 2

I try build after:
 yum install glib2-devel zlib-devel pcre-devel openssl-devel cmake

The cmake messages:
 cmake .
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using mysql-config: /bin/mysql_config
-- Found MySQL: /usr/include/mysql, /usr/lib64/libmysqlclient.so;/usr/lib64/libpthread.so;/usr/lib64/libm.so;/usr/lib64/libdl.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1")
-- checking for one of the modules 'glib-2.0'
-- checking for one of the modules 'gthread-2.0'
-- checking for module 'libpcre'
--   found libpcre, version 8.32
-- Found PCRE: /usr/include

CMake Warning at docs/CMakeLists.txt:9 (message):
  Unable to find Sphinx documentation generator

-- ------------------------------------------------
-- MYSQL_CONFIG = /bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
--
-- Configuring done
-- Generating done

**Comment by maxbube** [comment]
Hi @pilot513 you need to use mysql 5.7 libs

**Comment by pilot513** [comment]
If i compiled it with 5.7, but it work-server installed 5.6 (NDB 7.4.x) mydumper/loader will be work ?

**Comment by pilot513** [comment]
So. I want to ask. _How i can customize a query to split into sections (tables) not along the "RowId"?_

**Comment by maxbube** [comment]
Hi @pilot513 , 

I just merged a fix for your issue compiling against 5.6, it should work now for you, but I would recommend to install from the releases section as those packages are built static against mysql libs so you don't need to care about what version are you running.

About your last question that is not possible on actual mydumper, you can't specify a column. mydumper try to detect an integer index using PK, UNIQUE, INDEX order.

**Comment by pilot513** [comment]
Ok. Thanks
