### ISSUE TITLE
mydumper doesn't compile unmodified on Ubuntu 16.04

### ISSUE THREAD

**Issue by jonathantullett** [maxbube/mydumper#29]
The default generate makefile doesn't compile on Ubuntu 16.04. It complains of:
```
root@mysql2:/usr/local/src/mydumper# make
[ 16%] Linking C executable mydumper
/usr/bin/ld: CMakeFiles/mydumper.dir/mydumper.c.o: undefined reference to symbol 'ceilf@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/mydumper.dir/build.make:151: recipe for target 'mydumper' failed
make[2]: *** [mydumper] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mydumper.dir/all' failed
make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

Modifying CMakeLists.txt and adding `-lm` to the `target_link_libraries()` lines works:
```
target_link_libraries(mydumper ${MYSQL_LIBRARIES} ${GLIB2_LIBRARIES} ${GTHREAD2_LIBRARIES} ${PCRE_PCRE_LIBRARY} ${ZLIB_LIBRARIES} -lm)
```

I'm not up to speed with cmake to do this change properly and submit a pull request but hopefully it's enough here for someone to do that legwork.

Thanks!

**Comment by maxbube** [comment]
Hi @jonathantullett , not sure if this is still an issue for you, but I added packages in the release section, let me know if they work for you.
