### ISSUE TITLE
error: ‘MYSQL_TYPE_JSON’ undeclared

### ISSUE THREAD

**Issue by utdrmac** [maxbube/mydumper#86]
```
yum install glib2-devel mysql-devel zlib-devel pcre-devel openssl-devel cmake gcc gcc-c++

cmake .
...
[root@clx1-8 mydumper]# make
Scanning dependencies of target mydumper
[ 25%] Building C object CMakeFiles/mydumper.dir/mydumper.c.o
/mnt/mysqldump/mydumper/mydumper.c: In function ‘dump_table_data’:
/mnt/mysqldump/mydumper/mydumper.c:2814: error: ‘MYSQL_TYPE_JSON’ undeclared (first use in this function)
/mnt/mysqldump/mydumper/mydumper.c:2814: error: (Each undeclared identifier is reported only once
/mnt/mysqldump/mydumper/mydumper.c:2814: error: for each function it appears in.)
make[2]: *** [CMakeFiles/mydumper.dir/mydumper.c.o] Error 1
make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by utdrmac** [comment]
```
[root@clx1-8 mydumper]# cmake .
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL: /usr/include/mysql, /usr/lib64/mysql/libmysqlclient_r.so;/usr/lib64/libz.so;/usr/lib64/libpthread.so;/usr/lib64/libcrypt.so;/usr/lib64/libnsl.so;/usr/lib64/libm.so;/usr/lib64/libpthread.so;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.3")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23")
-- checking for one of the modules 'glib-2.0'
-- checking for one of the modules 'gthread-2.0'
-- checking for module 'libpcre'
--   found libpcre, version 7.8
-- Found PCRE: /usr/include

CMake Warning at docs/CMakeLists.txt:9 (message):
  Unable to find Sphinx documentation generator


-- ------------------------------------------------
-- MYSQL_CONFIG = /usr/bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
--
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/mysqldump/mydumper
```

**Comment by utdrmac** [comment]
```
[root@clx1-8 mydumper]# mysql --version
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
[root@clx1-8 mydumper]#
[root@clx1-8 mydumper]# cat /etc/redhat-release
CentOS release 6.8 (Final)

[root@clx1-8 mydumper]# rpm -qa | grep -i mysql
mysql-5.1.73-8.el6_8.x86_64
mysql-devel-5.1.73-8.el6_8.x86_64
MySQL-python-1.2.3-0.3.c1.1.el6.x86_64
mysql-libs-5.1.73-8.el6_8.x86_64
```

**Comment by utdrmac** [comment]
Used rpm package to install.

**Comment by maxbube** [comment]
For sure related to old mysql libs :)

**Comment by utdrmac** [comment]
I deleted the 2 lines referencing MYSQL_TYPE_JSON and compiled fine on older libs. I don't see any requirements in the compile instructions that a specific version is required. Maybe some IFDEF MYSQL_VERSION > 50700 for version checking to include JSON stuff?

**Comment by tsolodov** [comment]
I agree with previous post, I am working with 5.6 and had the same issue, could you please add this check in the source or Make file?

**Comment by pataquets** [comment]
@utdrmac @tsodolov : See #81

**Comment by rosmanov** [comment]
`10.1.29-MariaDB`:

```
$ make 
[ 16%] Building C object CMakeFiles/mydumper.dir/mydumper.c.o
/home/ruslan/src/mydumper/mydumper.c: In function ‘dump_table_data’:
/home/ruslan/src/mydumper/mydumper.c:2821:55: error: ‘MYSQL_TYPE_JSON’ undeclared (first use in this function)
                                 if (fields[i].type == MYSQL_TYPE_JSON) g_string_append(statement_row, "CONVERT(");
                                                       ^~~~~~~~~~~~~~~
/home/ruslan/src/mydumper/mydumper.c:2821:55: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/mydumper.dir/build.make:63: CMakeFiles/mydumper.dir/mydumper.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/mydumper.dir/all] Error 2
make: *** [Makefile:130: all] Error 2


```
