### ISSUE TITLE
MySQL libraries version for releases

### ISSUE THREAD

**Issue by davidducos** [maxbube/mydumper#330]
Yesterday, we release [v0.10.5](https://github.com/maxbube/mydumper/releases/tag/v0.10.5), and in the notes, I wrote:
```
On releases 0.10.1, 0.10.3 and 0.10.5, we compiled against MySQL 5.7 libraries (Percona fork) and packaged it.
Since release 0.10.5, we are also compiling against MySQL 8 libraries for testing purposes, not releasing.
```
I would like your opinion about next releases, should we releasing with both libraries? should we stop using 5.7?

**Comment by 3eka** [comment]
HI @davidducos,

IMHO you should keep it /5.7 libraries) for while. Guess not everybody have dropped MySQL/Percona 5.7.

Regards.

Thanks for releases! I was able to compile (and use) it on OpenIndiana, built against MariaDB 10.3:
`:; mydumper --version
mydumper 0.10.6, built against MySQL 10.3.24
`

**Comment by davidducos** [comment]
Hi @3eka, thanks! 
And what about both? for instance, release like this:
mydumper-0.10.5-1-57.el7.x86_64.rpm
mydumper-0.10.5-1-80.el7.x86_64.rpm
Or MariaDB... is it worthy?

**Comment by 3eka** [comment]
Hi @davidducos, 
maybe I am not proper person to discuss this with...

In any case, it is easy to build it. Who needs it... You cannot cover all possible cases/combinations.

Regards.

**Comment by mshedsilegx** [comment]
mydumper does not seem to compile with -DWITH_BINLOG=ON and MySQL 8.0 headers, due to the fact that my_global.h is removed in 8.0. The following error is shown:
binlog.c:23:10: fatal error: my_global.h: No such file or directory

Until this is resolved, I think we should stay with 5.7 mysql libs.
Best regards.

**Comment by davidducos** [comment]
I was able to fix the issues on 5.7 and I tried to make it work on 8.0 but the major issue is that the binlog.o needs to be build with c++ and even after doing that I had linking problems. This will need more time.
