### ISSUE TITLE
mydumper 0.9.3 fails to build with MariaDB 10.2

### ISSUE THREAD

**Issue by hydrapolic** [maxbube/mydumper#66]
Due to https://jira.mariadb.org/browse/MDEV-13773 this compilation error is printed when building with MariaDB 10.2.9:

````
# make
Scanning dependencies of target myloader
[ 12%] Building C object CMakeFiles/myloader.dir/myloader.c.o
/tmp/1/mydumper-0.9.3/myloader.c: In function 'main':
/tmp/1/mydumper-0.9.3/myloader.c:117:61: error: 'MYSQL_SERVER_VERSION' undeclared (first use in this function)
   g_print("myloader %s, built against MySQL %s\n", VERSION, MYSQL_SERVER_VERSION);
                                                             ^
/tmp/1/mydumper-0.9.3/myloader.c:117:61: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/myloader.dir/build.make:62: recipe for target 'CMakeFiles/myloader.dir/myloader.c.o' failed
make[2]: *** [CMakeFiles/myloader.dir/myloader.c.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/myloader.dir/all' failed
make[1]: *** [CMakeFiles/myloader.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
````

It is because MYSQL_SERVER_VERSION is not included. This works with both MariaDB 10.1 and MariaDB 10.2:
````
--- a/mydumper.c	2017-09-07 14:53:02.000000000 +0000
+++ b/mydumper.c	2017-10-06 17:39:34.962315949 +0000
@@ -22,6 +22,9 @@
 #define _FILE_OFFSET_BITS 64
 
 #include <mysql.h>
+#if defined(MARIADB_BASE_VERSION) && defined(MARIADB_VERSION_ID)
+	#include <server/mysql_version.h>
+#endif
 #include <unistd.h>
 #include <stdio.h>
 #include <string.h>
--- a/myloader.c	2017-09-07 14:53:02.000000000 +0000
+++ b/myloader.c	2017-10-06 17:39:28.962315949 +0000
@@ -19,6 +19,9 @@
 #define _FILE_OFFSET_BITS 64
 
 #include <mysql.h>
+#if defined(MARIADB_BASE_VERSION) && defined(MARIADB_VERSION_ID)
+	#include <server/mysql_version.h>
+#endif
 #include <unistd.h>
 #include <stdio.h>
 #include <string.h>
````

**Comment by maxbube** [comment]
Hi @hydrapolic you can use the packages Ive added to the latest release. Their are compiled static against mysql libs.

**Comment by hydrapolic** [comment]
Hello @maxbube, I forgot to mention that we're doing this on Linux Gentoo where we try to build everything from source.

Here is the source:
https://github.com/gentoo/gentoo/blob/master/dev-db/mydumper/mydumper-0.9.3-r1.ebuild

And the current patch:
https://github.com/gentoo/gentoo/blob/master/dev-db/mydumper/files/mydumper-mariadb-define.patch

**Comment by maxbube** [comment]
Hi @hydrapolic 

If you could push a PR so I can test the code for other releases would be great, if all succeed I will merge it

**Comment by hydrapolic** [comment]
https://github.com/maxbube/mydumper/pull/80

**Comment by maxbube** [comment]
Hi @hydrapolic thanks for the PR. I've already merged it.

**Comment by hydrapolic** [comment]
Thank you @maxbube
